---
services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
    environment: 
      LISTEN: ${CRAIT_BESZEL_LISTEN}
      KEY: ${CRAIT_BESZEL_KEY}
      TOKEN: ${CRAIT_BESZEL_TOKEN}
      HUB_URL: ${CRAIT_BESZEL_HUB_URL}
networks: {}