---
services:
  checkcle-server-agent:
    image: operacle/checkcle-server-agent:latest
    container_name: monitoring-agent
    restart: unless-stopped
    ports:
      - 8082:8081
    group_add:
      - "999"
    environment:
      - AGENT_ID="agent_6m9ybnmcgjgj8rt1wsoxx"
      - SERVER_NAME="crait"
      - SERVER_TOKEN="srv_ngolf66jqnogrrkeuzlas"
      - HOSTNAME="crait"
      - POCKETBASE_URL="http://192.168.0.25:8090"
      - POCKETBASE_ENABLED=true
    volumes:
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /var/run:/host/var/run:ro
      - /dev:/host/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_STORAGE_DIR}/monitoring_data:/var/lib/monitoring-agent
      - ${DOCKER_STORAGE_DIR}/monitoring_logs:/var/log/monitoring-agent
networks: {}
